### ISSUE TITLE
text lines diplaying and going beyond display borders

### ISSUE THREAD

**Issue by Sangeeth123sj** [rm-hull/luma.examples#115]
I have got a sparkfun's transparent display, and hooked it to raspberry pi using luma.oled
It displays text when I use draw.text() but the text doesn't display completely within the display, It just goes straight and dispalys the end of the text beyond the borders of display thus making it not seen,
Is there anyway I can make the rest of text go to the next line below it automatically?, please help

**Comment by thijstriemstra** [comment]
can you share your code?

**Comment by rm-hull** [comment]
No response ... closing

**Comment by Sangeeth123sj** [comment]
sorry for not responding, had got it fixed myself
