### ISSUE TITLE
No module named luma.core

### ISSUE THREAD

**Issue by bennetdev** [rm-hull/luma.examples#117]
I have followed all the required steps. I can run the examples with the python command, but if I use python3 it says "No module named 'luma.core'". I have used pip3 show luma.core and pip3 install luma.core trying to fix it but I am certain that luma.core for python3 is installed on my raspberry. Any tips?

**Comment by bennetdev** [comment]
Also pip3 show luma.core shows this location:" /usr/local/lib/python3.7/dist-packages/luma.core-1.14.0-py3.7.egg" which I don't know wether its normal.

**Comment by rm-hull** [comment]
Which version of raspian?
What does `python --version` show?
What does `python3 --version` show?

**Comment by bennetdev** [comment]
raspbian version is the latest one (Version 10 buster)
python version 2.7.16
python3 version 3.7.3

**Comment by thijstriemstra** [comment]
can you try running python3 and then 'import luma.core'?

**Comment by thijstriemstra** [comment]
no feedback, closing.
