### ISSUE TITLE
Error in installing max7219

### ISSUE THREAD

**Issue by ThivagarK** [rm-hull/luma.examples#122]
I try to install max7219 but it shows this ;
sudo pip3 install max7219
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting max7219
Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://pypi.org/simple/max7219/

**Comment by rm-hull** [comment]
max7219 is long since deprecated. I assume you are following some tutorial on the web from a long time ago. Please look at its replacement https://pypi.org/project/luma.led_matrix/ and follow its installation instructions instead.
