### ISSUE TITLE
Test demo_opts

### ISSUE THREAD

**Issue by thijstriemstra** [rm-hull/luma.examples#13]
We should add unit tests to make sure nothing breaks in the argument parser.

**Comment by thijstriemstra** [comment]
Also related to #5

**Comment by thijstriemstra** [comment]
@rm-hull can you enable travis for this repo?

**Comment by rm-hull** [comment]
Should be enabled now: https://travis-ci.org/rm-hull/luma.examples

**Comment by thijstriemstra** [comment]
Thanks. Now to write some tests: https://travis-ci.org/rm-hull/luma.examples/jobs/205996186
