### ISSUE TITLE
OLED SSD1306

### ISSUE THREAD

**Issue by ruozhiertong** [rm-hull/luma.examples#135]
My situation:
Pi 4B with2020-08-20-raspios-buster-armhf , Python3,  0.9 inch OLED with SSD1306.
When i run : python3 demo.py
There is an error:
demo.py: error: Invalid/unsupported framebuffer: /dev/fd0.
How to fix the error?
Thx.

**Comment by rm-hull** [comment]
python3 demo.py -d ssd1306

**Comment by rm-hull** [comment]
There was a regression in luma.core that caused this.. it should default to SSD1306, I will apply a fix now

**Comment by rm-hull** [comment]
luma.core 2.0.2 released with a fix for this

**Comment by mguzelocak** [comment]
I have this problem with Pi 5. What should I do to fix the error?

when i run the file i got this error:
maze.py: error: Invalid/unsupported framebuffer: /dev/fd0

then i run it again with this command:
mcguzelocak@raspberrypi1:/home/mcguzelocak/luma.examples/examples$ python3 demo.py -d ssd1306

and I got his error:
demo.py: error: argument --display/-d: invalid choice: 'ssd1306' (choose from 'linux_framebuffer')
