### ISSUE TITLE
Weather.py not working

### ISSUE THREAD

**Issue by tarmacalastair** [rm-hull/luma.examples#141]
Hi,

I've just got an Odroid board with and OLED screen and was keen to try these examples. However the URL for getting BBC weather is out of date.
The old URL line in the script is `weather_rss_url = "http://open.live.bbc.co.uk/weather/feeds/en/{0}/3dayforecast.rss".format(location_id)`

You need to replace this with: `weather_rss_url = "https://weather-broker-cdn.api.bbci.co.uk/en/forecast/rss/3day/{0}".format(location_id)`

I also copied the script to produce a BBC news feed using this line:
    `weather_rss_url = "http://feeds.bbci.co.uk/news/rss.xml"`
Presumably you could replace this with lots of different RSS feeds?

I struggle to read the small font in this script. Can anyone advise how to make it bigger please?
Thanks

**Comment by thijstriemstra** [comment]
thanks! want to make a pull request with that change?
