### ISSUE TITLE
Pi Zero 2 W, cannot open resource

### ISSUE THREAD

**Issue by geertheuvels** [rm-hull/luma.examples#169]
I am using a SH1106 oled. Works fine on a Raspberry 2B. I installed my software on a Pi Zero 2 W, now I get the error: cannot open resource.  On the Zero, i2c is enabled, i2cdetect -y 1 returns correct 0x3C address. All libs are installed without errors.
Any idea?

**Comment by thijstriemstra** [comment]
what python version, operating system version, etc

**Comment by geertheuvels** [comment]
But it works now, sorry for disturbing. 
But it works now, sorry for disturbing. 
Raspberry Pi OS, 64-bit Lite (releasedate 2023-12-05). 
Python 3.9.2 (latest version for this OS).
SDS011 dustsensor via USB.

But it works now I installed again the long list of libs according to the docs. Must have been a typo, but did not see an error message.
Sorry for disturbing. Thanks for your very quick response!
