### ISSUE TITLE
fontawesome icons example

### ISSUE THREAD

**Issue by thijstriemstra** [rm-hull/luma.examples#26]
Would be cool to have a [fontawesome](http://fontawesome.io/) example that demonstrates how to render their icons (on an oled screen).

**Comment by thijstriemstra** [comment]
was about to start with this ha, but I'll pick up another issue. Looking forward to this example!

I would like to have something that displays all of the icons one by one, with a few seconds delay, with a large icon centered on the screen and the icon name below it or something?

**Comment by rm-hull** [comment]
> I would like to have something that displays all of the icons one by one, 

check

> with a few seconds delay, 

check

> with a large icon centered on the screen 

check

> and the icon name below it 

ah...

😆

**Comment by thijstriemstra** [comment]
It's not mentioned in the readme.
