### ISSUE TITLE
Font rendering scripts fail to execute.

### ISSUE THREAD

**Issue by somu1795** [rm-hull/luma.examples#33]
The scripts which use fonts from the "fonts" folder included in examples, fail to execute.
It raises IOError - unknown file format.
```
Display: pcd8544
Interface: spi
Dimensions: 128 x 64
----------------------------------------
Traceback (most recent call last):
  File "welcome.py", line 233, in <module>
    main()
  File "welcome.py", line 198, in main
    fonts = [make_font("code2000.ttf", sz) for sz in range(24, 8, -2)]
  File "welcome.py", line 121, in make_font
    return ImageFont.truetype(font_path, size)
  File "/usr/local/lib/python2.7/dist-packages/PIL/ImageFont.py", line 238, in truetype
    return FreeTypeFont(font, size, index, encoding)
  File "/usr/local/lib/python2.7/dist-packages/PIL/ImageFont.py", line 127, in __init__
    self.font = core.getfont(font, size, index, encoding)
IOError: unknown file format

```

It seems, imagefont is unable to load fonts  from anywhere else except the default folders, i.e -
 "/usr/share/fonts/truetype/freefont/"
After copying the individual fonts to the above mentioned folder, the script works flawlessly, also the provided "code2000.ttf" font is corrupt, I downloaded a fresh copy of the "code2000.ttf" from internet , after copying to the default folder , it works.

**Comment by thijstriemstra** [comment]
@somu1795 what operating system, python version, pygame version etc?

**Comment by somu1795** [comment]
OS: raspbian latest
Python - 2.7.9
Pygame - 1.9.3
I updated the issue with the error included.

**Comment by thijstriemstra** [comment]
can you show `ls -l` for corrupt and correct code2000.ttf? and where did you get a fresh copy?

**Comment by somu1795** [comment]
```
$ ls -l
total 6224
-rwxr-xr-x 1 root root   49432 Mar 21 07:42 C&C Red Alert [INET].ttf
-rwxr-xr-x 1 root root 2686976 Mar 21 07:42 code2000_bak.ttf
-rwxr-xr-x 1 root root 3155104 Feb  3  2010 code2000.ttf
-rwxr-xr-x 1 root root   85484 Mar 21 07:42 creep.bdf
-rwxr-xr-x 1 root root  165548 Mar 21 07:42 fontawesome-webfont.ttf
-rwxr-xr-x 1 root root   64880 Mar 21 07:42 FreePixel.ttf
-rwxr-xr-x 1 root root   23280 Mar 21 07:42 miscfs_.ttf
-rwxr-xr-x 1 root root   22184 Mar 21 07:42 pixelmix.ttf
-rwxr-xr-x 1 root root   35656 Mar 21 07:42 ProggyTiny.ttf
-rwxr-xr-x 1 root root    2847 Mar 21 07:42 README [INET].txt
-rwxr-xr-x 1 root root    6656 Mar 21 07:42 tiny.ttf
-rwxr-xr-x 1 root root   55580 Mar 21 07:42 Volter__28Goldfish_29.ttf

```
The "code2000_bak.ttf" is the corrupt aka original one provided, and "code2000.ttf" is the new one downloaded from - [http://www.fonts2u.com/code2000.font](url)

**Comment by thijstriemstra** [comment]
Hmm.. Ubuntu 16.04, latest git master for examples:

```
$ ls -l ../luma.examples/examples/fonts/
total 8700
-rw-rw-r-- 1 thijs thijs   49432 feb 27 23:59 C&C Red Alert [INET].ttf
-rw-rw-r-- 1 thijs thijs 8377000 feb 27 23:59 code2000.ttf
-rw-rw-r-- 1 thijs thijs   85484 feb 27 23:59 creep.bdf
-rw-rw-r-- 1 thijs thijs  165548 mrt 15 21:37 fontawesome-webfont.ttf
-rw-rw-r-- 1 thijs thijs   64880 feb 27 23:59 FreePixel.ttf
-rw-rw-r-- 1 thijs thijs   23280 feb 27 23:59 miscfs_.ttf
-rwxrwxr-x 1 thijs thijs   22184 feb 27 23:59 pixelmix.ttf
-rw-rw-r-- 1 thijs thijs   35656 feb 27 23:59 ProggyTiny.ttf
-rw-rw-r-- 1 thijs thijs    2847 feb 27 23:59 README [INET].txt
-rw-rw-r-- 1 thijs thijs    6656 feb 27 23:59 tiny.ttf
-rw-rw-r-- 1 thijs thijs   55580 feb 27 23:59 Volter__28Goldfish_29.ttf
```

**Comment by thijstriemstra** [comment]
And git shows 7.9 MB: https://github.com/rm-hull/luma.examples/blob/master/examples/fonts/code2000.ttf so I think it got corrupted during your git checkout? Can you try to clone it again?

**Comment by somu1795** [comment]
After cloning again, I do get the correct code2000.ttf 
```
$ ls -l
total 516
-rwxr-xr-x 1 root root   49432 Mar 22 20:04 C&C Red Alert [INET].ttf
-rwxr-xr-x 1 root root 8377000 Mar 22 20:04 code2000.ttf
-rwxr-xr-x 1 root root   85484 Mar 22 20:04 creep.bdf
-rwxr-xr-x 1 root root  165548 Mar 22 20:05 fontawesome-webfont.ttf
-rwxr-xr-x 1 root root   64880 Mar 22 20:04 FreePixel.ttf
-rwxr-xr-x 1 root root   23280 Mar 22 20:05 miscfs_.ttf
-rwxr-xr-x 1 root root   22184 Mar 22 20:05 pixelmix.ttf
-rwxr-xr-x 1 root root   35656 Mar 22 20:04 ProggyTiny.ttf
-rwxr-xr-x 1 root root    2847 Mar 22 20:04 README [INET].txt
-rwxr-xr-x 1 root root    6656 Mar 22 20:05 tiny.ttf
-rwxr-xr-x 1 root root   55580 Mar 22 20:04 Volter__28Goldfish_29.ttf

```

**Comment by somu1795** [comment]
Thanks , it works after getting the fresh repository.
I downloaded the zip file instead of cloning this time , and everything works correctly.
Also I had to install the pygame through apt-get : 
`$ sudo apt-get install python-pygame`
Installing through the default installer script generates error, "sdl-config" not found.

**Comment by thijstriemstra** [comment]
> Also in pcd8544.conf the default SPI speed is 32Mhz , but with this setting the display remains blank , it works upto a max of 8Mhz.
@rm-hull is this a bug?

**Comment by rm-hull** [comment]
So its a trade off, 32MHz obviously transfers data quicker but is subject to cross chatter and interference - and the vagaries of the different breakout boards out there. It works for me, but other boards I have to crank it down to 16MHz to get it to work.

Maybe the conf file settings should be more conservative ... PR happily accepted @somu1795 :)

**Comment by somu1795** [comment]
Thank You 👍

**Comment by rm-hull** [comment]
re. the sdl-config, we're in the process of overhauling the docs into one place - at the moment its spread (and partially repeated) over 4 or 5 doc sites, but AFAIR following https://luma-emulator.readthedocs.io/en/latest/install.html#installing-from-pypi should be sufficient to install the latest pygame.

**Comment by somu1795** [comment]
Aha! Thanks for that !
