### ISSUE TITLE
Installation instructions do not work

### ISSUE THREAD

**Issue by fiveseven808** [rm-hull/luma.examples#36]
I followed:
$ sudo usermod -a -G i2c,spi,gpio pi
$ sudo apt-get install python-dev python-pip libfreetype6-dev libjpeg-dev
$ sudo apt-get purge python-pip
$ sudo -H pip install --upgrade pip

However, the last command results in:
`sudo: pip: command not found`

**Comment by rm-hull** [comment]
Oops - good spot: it looks like those last two commands were the wrong way round. Should be fixed now in the README.

You should be able to do:

    $ sudo apt-get install python-pip
    $ sudo -H pip install --upgrade pip
    $ sudo apt-purge python-pip

and then check it with:

    $ pip --version
    pip 9.0.1 from /usr/local/lib/python2.7/site-packages (python 2.7)

**Comment by fiveseven808** [comment]
Thank you! I will try that!

**Comment by fiveseven808** [comment]
It worked perfectly! Thanks!
