### ISSUE TITLE
PiCamera example

### ISSUE THREAD

**Issue by thijstriemstra** [rm-hull/luma.examples#4]
picamera live stream -> luma -> oled/lcd etc..

**Comment by rm-hull** [comment]
@thijstriemstra - have a look at what @bjerrep is doing with gstreamer: https://github.com/bjerrep/ssd1306#television - amazing stuff!

**Comment by thijstriemstra** [comment]
Wow that's awesome!

**Comment by rm-hull** [comment]
Also, work is coming on with the led_matrix revamp, including a new emulator transformer:

![ezgif com-optimize 1](https://cloud.githubusercontent.com/assets/1915543/22001630/523cc436-dc3e-11e6-86d0-ebf0b93e6c95.gif)

```
$ cat led_matrix.conf 
--display=gifanim
--transform=led_matrix
--height=8
--width=40
--scale=16
--mode=1
--max-frames=375
--duration=0.05

$ python examples/tweet_scroll.py -f led_matrix.conf 
```

**Comment by thijstriemstra** [comment]
@rm-hull Got it to work and it's magical: https://youtu.be/A9psiIqRNnc

Going to create a branch with these new examples now.

**Comment by thijstriemstra** [comment]
Branch is at `picamera-4`. Do you have a camera to test with @rm-hull?

**Comment by rm-hull** [comment]
Awesome stuff!
would be interesting to try and integrate it in with @bjerrep's gstreamer television code.

Haven't got a Pi camera though... 😭

**Comment by thijstriemstra** [comment]
Ah too bad, they're only 5 bucks though ;) http://www.ebay.com/itm/191823838867?_trksid=p2055119.m1438.l2649&ssPageName=STRK%3AMEBIDX%3AIT
