### ISSUE TITLE
Questions on how the program "cleans up"

### ISSUE THREAD

**Issue by fiveseven808** [rm-hull/luma.examples#41]
This is not an issue. I'd like to ask the maintainer some questions to clarify how this works? Is there any communication channel I can reach rm-hull? 

I'd like to know how luma cleans up the display interfaces when done, i.e. blanks the screen and it also appears to sort of "release" the interface. 

If I have a program running and using the interface (via the Adafruit SSD1306 driver) and then call a luma example, both work and compete (but work) for the display interface, but when I terminate the luma example, my program can no longer access the display. 

Can anyone tell me the mechanism that prevents my program from continued use of the display? 

Ideally, I'd like to give multiple programs access to the display (of course not at the same time). I'd be managing them myself (unless this driver has a way to manage that?) I plan to port my code using the Adafruit driver to the luma driver, but ideally, I'd like to sort this whole "clean up" but out first, so that programs still running in the background can regain control of the display. 

Thanks!

**Comment by rm-hull** [comment]
Raising an issue if you have a question is the right communications channel.

So a design decision was taken to power down the various devices when the program terminates - this obviously closes and connections and puts the device into a state where it is either off or in a low-power state. This was done mainly to help prolong the life of the device.

If you want to be able to keep the device on after the program is terminated, there is currently no official way to do this, but if you have a look at the discourse in https://github.com/rm-hull/luma.oled/issues/140, in there is a example of how you can do that in the meantime.
