### ISSUE TITLE
clock example incorrectly aligned

### ISSUE THREAD

**Issue by thijstriemstra** [rm-hull/luma.examples#49]
The clock example isn't correctly centered on a 128*160 st7735 lcd.

**Comment by rm-hull** [comment]
and the clock in the carousel example is properly banjaxed at that resolution too 😵

**Comment by thijstriemstra** [comment]
i didn't even test that one, weird; but haha yea that's screwed up.

**Comment by thijstriemstra** [comment]
Can you take a look at this @rm-hull?

**Comment by rm-hull** [comment]
shall do

**Comment by thijstriemstra** [comment]
Cheers
