### ISSUE TITLE
Move extra dependencies to setup.py

### ISSUE THREAD

**Issue by thijstriemstra** [rm-hull/luma.examples#53]
Some examples have extra dependencies (e.g. picamera, psutil, feedparser, etc). Shouldn't these belong in the setup.py, and be installed when the examples are installed? It's more to install but easier for newbies.

**Comment by rm-hull** [comment]
Yes, think you're right & it can't harm

**Comment by thijstriemstra** [comment]
I think we shouldn't do this, it's bloat, please re-open if you object.
