### ISSUE TITLE
sevensegment_demo.py fails

### ISSUE THREAD

**Issue by CoWinkKeyDinkInc** [rm-hull/luma.examples#71]
```
pi@raspberrypi:~/Git/luma.examples/examples $ python sevensegment_demo.py
Version: luma.oled 2.3.1 (luma.core 1.2.1)
Display: ssd1306
Interface: i2c
Dimensions: 128 x 64
------------------------------------------------------------
Traceback (most recent call last):
  File "sevensegment_demo.py", line 115, in <module>
    main()
  File "sevensegment_demo.py", line 71, in main
    seg = sevensegment(device)
  File "/usr/local/lib/python2.7/dist-packages/luma/core/virtual.py", line 482, in __init__
    self.segment_mapper = segment_mapper or device.segment_mapper
AttributeError: 'ssd1306' object has no attribute 'segment_mapper'

```

**Comment by rm-hull** [comment]
This is to be expected; ssd1306 is not a device that has the capability for supporting 7-segment displays - only max7219 or ht1621 does.

**Comment by thijstriemstra** [comment]
we could put a check in there that produces a good error msg..

**Comment by CoWinkKeyDinkInc** [comment]
Oh sorry about that, but yeah thanks for adding a more clear error message.

**Comment by thijstriemstra** [comment]
> the capability for supporting 7-segment displays - only max7219 or ht1621 does.

@rm-hull are you sure these are the only ones? I opened for #76 this. Unfortunately we'll have to update the demo every time another supported device is added..
