### ISSUE TITLE
[question] Framebuffer

### ISSUE THREAD

**Issue by nagualcode** [rm-hull/luma.examples#86]
How can I run these examples on the raspberry frambuffer (HDMI output)  ?

**Comment by thijstriemstra** [comment]
I don't think you can, but @rm-hull knows more about this.

**Comment by rm-hull** [comment]
Yes, make sure pygame is installed and run the examples with `-d pygame`

**Comment by rm-hull** [comment]
Note you also need to `pip install luma.emulator`

**Comment by thijstriemstra** [comment]
@nagualcode I thought you wanted to run it using HDMI. Try running the sample without ssh.

**Comment by nagualcode** [comment]
Yep, the monitor is attached via HDMI.
I dont have a USB keyboard... Only ssh access.
Also,  I dont have X server installed, do I need it?
