### ISSUE TITLE
Command line description for --interface

### ISSUE THREAD

**Issue by thomasw-mitutoyo-ctl** [rm-hull/luma.examples#96]
The help says that there's an optional parameter

```[--interface]```

Later it says

```
--interface , -i      Serial interface type. Allowed values are: i2c, spi,
                        bitbang (default: i2c)
```

So, if that parameter needs values, it should read

```[--interface VALUE]```

where VALUE can be replaced by i2c, spi or bitbang.

**Comment by thomasw-mitutoyo-ctl** [comment]
The same applies for `--display`, `--rotate`, `--block-orientation`, `--mode`, `--framebuffer`, `--backlight-active` and `--transform`

**Comment by thijstriemstra** [comment]
Looks like this is a limitation of the argparse Python module.. not sure what to do about it.

**Comment by thijstriemstra** [comment]
Yea, removing metavar fixes it:

```
  --interface {i2c,spi,bitbang}, -i {i2c,spi,bitbang}
                        Serial interface type. Allowed values are: i2c, spi,
                        bitbang (default: i2c)
```

**Comment by thijstriemstra** [comment]
> The help says that there's an optional parameter

it's optional because you can use the `--config` parameter and specify all params there.
