### ISSUE TITLE
NameError for text() in Luma example

### ISSUE THREAD

**Issue by thomasw-mitutoyo-ctl** [rm-hull/luma.examples#98]
The LED example for daisy chaining at https://luma-led-matrix.readthedocs.io/en/latest/python-usage.html#daisy-chaining has a two lines of code that 

```
text(draw, (2, 2), "Hello", fill="white", font=proportional(LCD_FONT))
text(draw, (2, 10), "World", fill="white", font=proportional(LCD_FONT))
```

It seems there's missing

```
from luma.core.legacy import text
```

**Comment by thijstriemstra** [comment]
Thanks. Can you create a pull request?
